[vcs]
type = "git"

[semver]
version = "0.13.1"
bump_commit_message_template = "bump: {prev_version_str} -> {version_str} [skip ci]"
version_tag_name_template = "v{version_str}"

[hook]
paths = [".bumpify/commit_parser_hook.py"]

[[semver.bump_rules]]
branch = "misc/migrate-to-github"
when_breaking = "minor"
when_feat = "minor"
when_fix = "patch"

[[semver.version_files]]
path = "pyproject.toml"
prefix = "version"
section = "[tool.poetry]"
encoding = "utf-8"

[[semver.version_files]]
path = "mockify/__init__.py"
prefix = "__version__"
encoding = "utf-8"

[[semver.changelog_files]]
path = "CHANGELOG.md"
encoding = "utf-8"
