version: 2.1

jobs:

  install:
    docker:
      - image: cimg/python:<<parameters.version>>
    parameters:
      version:
        type: string
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "pipenv install --dev"

  test:
    docker:
      - image: cimg/python:<<parameters.version>>
    parameters:
      version:
        type: string
    steps:
      - checkout
      - run:
          name: "Run tests for Python <<parameters.version>>"
          command: "inv test"

workflows:

  test-workflow:
    jobs:
      - install:
          version: "3.6"
      - test:
          version: "3.6"
