version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python
    parameters:
      version:
        type: string
    steps:
      - checkout
      - run: |
          pipenv install --dev
          pipenv run inv tox -p

workflows:
  test-workflow:
    jobs:
      - test:
          version: "3.6"
