version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.version>>
    parameters:
      version:
        type: string
    steps:
      - checkout
      - run: |
          pipenv --python <<parameters.version>> install --dev
          inv tox -e <<parameters.version>>

workflows:
  test-workflow:
    jobs:
      - test:
          version: "3.6"
