version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.version>>
    parameters:
      version:
        type: string
      toxenv:
        type: string
    steps:
      - checkout
      - run: |
          pipenv --python <<parameters.version>> install --skip-lock --dev
          pipenv run inv tox -e <<parameters.toxenv>>

workflows:
  test:
    jobs:
      - test:
          version: "3.6"
          toxenv: "py36"
      - test:
          version: "3.7"
          toxenv: "py37"
