version: 2.1

jobs:
  test:
    docker:
      - image: <<parameters.image>>
    parameters:
      image:
        type: string
      envname:
        type: string
    steps:
      - checkout
      - run: |
          pipenv install --skip-lock --dev
          pipenv run inv tox -e <<parameters.envname>>

workflows:
  test-workflow:
    jobs:
      - test:
          image: "cimg/python:3.6"
          envname: "py36"
      - test:
          image: "cimg/python:3.7"
          envname: "py37"
